[package]
name = "d_anime_discord_presence"
version = "0.1.0"
edition = "2021"

[dependencies]
ctrlc = "3.4.4"
discord-sdk = "0.3.7"
serde = "1.0.204"
serde_json = "1.0.121"
tokio = { version = "1.39.2", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
